# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "hugo-theme-evkx2"
license = "MIT"
licenselink = "https://github.com/evkx/hugo-theme-evkx/blob/master/LICENSE.md"
description = "evkx theme for Hugo"
homepage = "https://github.com/evkx/hugo-theme-evkx"
repo = "https://github.com/evkx/hugo-theme-evkx"
tags = ["documentation", "menu","slide","search"]
features = ["documentation","menu","nested sections","search","slide", "attachments"]
min_version = "0.121.2"

[author]
  name = "evkx"
  homepage = "https://evkx.net"

[original]
  name = "Docdock"
  homepage = "https://docdock.netlify.com/"
  repo = "https://github.com/vjeantet/hugo-theme-docdock"
  licenselink = "https://github.com/vjeantet/hugo-theme-docdock/blob/master/LICENSE.md"